name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        working-directory: ./server
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: sohui.dev/to-do-list-react
          stage: main
          yaml: |
            name: to-do-list-react
            app: node@20
            options:
              env:
                - name: NODE_ENV
                  value: production
              ports: "3001"
              install: npm i --production
              build: ""
              start: node index.js
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: node
